spring.datasource.url=jdbc:h2:mem:meuslivros;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.mvc.hiddenmethod.filter.enabled=true

# Use this profile for fast local runs (mvn spring-boot:run -Dspring-boot.run.profiles=local)